config/routes.rb
Rails.application.routes.draw do
  
  resources :equipaments
  resources :equipamentusers
  resources :users
  
  root 'sessions#new'
  
  get 'sessions/new'

  get 'users/new'
  
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :sensors
  
  namespace :api , defaults: {format: :json} do 
    namespace :v1 do 
      resources :sensors
    end 
  end
end

app/models/equipamentuser.rb
class Equipamentuser < ApplicationRecord
  belongs_to :equipament
  belongs_to :user
  validates :equipament_id, uniqueness: { scope: :user_id }
end

app/controllers/equipamentusers_controller.rb
class EquipamentusersController < ApplicationController
  before_filter :authorize_user
  before_action :set_equipamentuser, only: [:show, :edit, :update, :destroy]

  # GET /equipaments
  # GET /equipaments.json
  def index
    if session[:user_type] == 'A'
      @equipamentusers = Equipamentuser.all
    else
      @equipamentusers = Equipamentuser.where(user_id: session[:user_id])  
    end
  end

  # GET /equipaments/1
  # GET /equipaments/1.json
  def show
    @equipamentuser = Equipamentuser.find(params[:id])
  end

  # GET /equipaments/new
  def new
    @equipamentuser = Equipamentuser.new
  end

  # POST /equipaments
  # POST /equipaments.json
  def create
    @equipamentuser = Equipamentuser.new(equipamentuser_params)
    
    respond_to do |format|
      if @equipamentuser.save
        format.html { redirect_to equipamentusers_url, notice: 'Equipamento associado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  # DELETE /equipaments/1
  # DELETE /equipaments/1.json
  def destroy
    @equipamentuser.destroy
    respond_to do |format|
      format.html { redirect_to equipamentusers_url, notice: 'Associação deletada com sucesso.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipamentuser
      @equipamentuser = Equipamentuser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipamentuser_params
      params.require(:equipamentuser).permit(:equipament_id, :user_id)
    end
  
    def authorize_user
      unless current_user
        redirect_to root_path
      end
    end
end

app/helpers/equipamentusers_helper.rb
module EquipamentusersHelper
end

app/views/equipamentusers/_form.html.erb
<br>
  <%= form_for(equipamentuser) do |f| %>
  
    <%= render 'shared/equipamentusers_error_messages' %>
    
    <%= f.select :equipament_id, Equipament.all.collect { |p| [ p.nome, p.id ] }, {prompt: 'Selecione o equipamento'}, {class: 'form-control'} %>
    
    <%= f.select :user_id, User.all.collect { |p| [ p.name, p.id ] }, {prompt: 'Selecione o usuário'}, {class: 'form-control'} %>
  
    <%= f.submit "Associar", class: "btn btn-primary" %>
    
  <% end %>
<br>

app/views/equipamentusers/index.html.erb
<% provide(:title, 'Meus equipamentos') %>

<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Equipamento</th>
      <th>Usuário</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipamentusers.each do |equipamentuser| %>
      <tr>
        <td><%= link_to equipamentuser.equipament.nome, sensors_path(chave: equipamentuser.equipament.chave, ativa: 'D', auxdata: Date.today.strftime("%d/%m/%Y")) %></td>
        <td><%= equipamentuser.user.name %></td>
        <% if session[:user_type] == 'A' %>
          <td><%= link_to 'Excluir', equipamentuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/equipamentusers/new.html.erb
<% provide(:title, 'Associar equipamentos') %>

<div class="divform">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form', equipamentuser: @equipamentuser %>
    </div>
  </div>
</div>
      
    