config/routes.rb
Rails.application.routes.draw do
  
  resources :equipaments
  resources :equipamentusers
  resources :users
  
  root 'sessions#new'
  
  get 'sessions/new'

  get 'users/new'
  
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :sensors
  
  namespace :api , defaults: {format: :json} do 
    namespace :v1 do 
      resources :sensors
    end 
  end
end

app/models/equipament.rb
class Equipament < ApplicationRecord
  
  has_many :equipamentusers
  has_many :users, through: :equipamentusers
  
  validates :chave, presence: true, uniqueness: { case_sensitive: false }
  validates :nome, presence: true
  validates :cidade, presence: true
  validates :estado, presence: true
  
end

app/controllers/equipaments_controller.rb
class EquipamentsController < ApplicationController
  before_filter :authorize_user
  before_action :set_equipament, only: [:show, :edit, :update, :destroy]

  # GET /equipaments
  # GET /equipaments.json
  def index
    @equipaments = Equipament.all
  end

  # GET /equipaments/new
  def new
    @equipament = Equipament.new
  end
  
  # POST /equipaments
  # POST /equipaments.json
  def create
    @equipament = Equipament.new(equipament_params)
    
    respond_to do |format|
      if @equipament.save
        format.html { redirect_to equipaments_url, notice: 'Equipamento criado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  # GET /equipaments/1/edit
  def edit
  end

  # PATCH/PUT /equipaments/1
  # PATCH/PUT /equipaments/1.json
  def update
    respond_to do |format|
      if @equipament.update(equipament_params)
        format.html { redirect_to equipaments_url, notice: 'Equipamento alterado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /equipaments/1
  # DELETE /equipaments/1.json
  def destroy
    @equipament.destroy
    respond_to do |format|
      format.html { redirect_to equipaments_url, notice: 'Equipamento deletado com sucesso.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipament
      @equipament = Equipament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipament_params
      params.require(:equipament).permit(:chave, :nome, :cidade, :estado)
    end
    
    def authorize_user
      unless current_user
        redirect_to root_path
      end
    end
    
  # GET /equipaments/1
  # GET /equipaments/1.json
  #def show
  #  @equipament = Equipament.find(params[:id])
  #end
  
end

app/helpers/equipaments_helper.rb
module EquipamentsHelper
end

app/views/equipaments/_form.html.erb
<br>
<%= form_for(equipament) do |f| %>

  <%= render 'shared/equipaments_error_messages' %>
  
  <%= f.text_field :chave, class: 'form-control', placeholder: 'Chave do equipamento' %>

  <%= f.text_field :nome, class: 'form-control', placeholder: 'Descrição' %>

  <%= f.text_field :cidade, class: 'form-control', placeholder: 'Cidade' %>

  <%= f.select(:estado, [['São Paulo', 'SP']], {prompt: 'Selecione o estado'}, {class: 'form-control'}) %>
  
  <%= f.submit "Criar equipamento", class: "btn btn-primary" %>
  
<% end %>
<br>

app/views/equipaments/edit.html.erb
<% provide(:title, 'Editar equipamento') %>

<div class="divform">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <br>
      
      <%= form_for(@equipament) do |f| %>
    
      <%= render 'shared/equipaments_error_messages' %>
      
      <label>Chave </label>
      <%= f.text_field :chave, class: 'form-control', placeholder: 'Chave do equipamento' %>
    
      <label>Descrição </label>
      <%= f.text_field :nome, class: 'form-control', placeholder: 'Descrição' %>
    
      <label>Cidade </label>
      <%= f.text_field :cidade, class: 'form-control', placeholder: 'Cidade' %>
      
      <label>Estado </label>
      <%= f.select(:estado, [['São Paulo', 'SP']], {prompt: 'Selecione o estado'}, {class: 'form-control'}) %>
      
      <%= f.submit "Alterar equipamento", class: "btn btn-primary" %>
      
      <% end %>
      
      <br>
    </div>
  </div>
</div>

app/views/equipaments/index.html.erb
<% provide(:title, 'Equipamentos') %>

<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipaments.each do |equipament| %>
      <tr>
        <td><%= equipament.nome %></td>
        <td><%= equipament.cidade %></td>
        <td><%= equipament.estado %></td>
        <td><%= link_to 'Editar', edit_equipament_path(equipament) %></td>
        <td><%= link_to 'Excluir', equipament, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo equipamento', new_equipament_path %>

app/views/equipaments/new.html.erb
<% provide(:title, 'Novo equipamento') %>

<div class="divform">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form', equipament: @equipament %>
    </div>
  </div>
</div>