config/routes.rb
Rails.application.routes.draw do
  
  resources :equipaments
  resources :equipamentusers
  resources :users
  
  root 'sessions#new'
  
  get 'sessions/new'

  get 'users/new'
  
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :sensors
  
  namespace :api , defaults: {format: :json} do 
    namespace :v1 do 
      resources :sensors
    end 
  end
end

app/models/user.rb
class User < ApplicationRecord
  #attr_accessible :name
  has_many :equipamentusers
  has_many :equipaments, through: :equipamentusers
  
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :usertype, presence: true, length: { maximum: 1 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 , maximum: 10 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize_user
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)    # Not the final implementation!
    
    if @user.save
      flash[:success] = "Usuário incluído com sucesso!"
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'Usuário alterado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :usertype)
    end
    
    def authorize_user
      unless current_user
        if User.first != nil
          redirect_to root_path
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, 'Editar usuário') %>

<div class="divform">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <br>
      
      <%= form_for(@user) do |f| %>
    
      <%= render 'shared/error_messages' %>
      
      <label>Nome </label>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Nome' %>
  
      <label>E-mail </label>
      <%= f.email_field :email, class: 'form-control', placeholder: 'E-mail' %>

      <label>Tipo </label>
      <%= f.select(:usertype, [['Administrador', 'A'], ['Usuário', 'U']], {prompt: 'Selecione o tipo'}, {class: 'form-control'}) %>
      
      <label>Senha </label>
      <%= f.password_field :password, class: 'form-control', placeholder: 'Crie uma senha' %>

      <label>Confirmar senha </label>
      <%= f.password_field :password_confirmation, class: 'form-control', placeholder: ' Confirme a senha' %>

      <%= f.submit "Alterar usuário", class: "btn btn-primary" %>
      
      <% end %>
      
      <br>
      
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Usuários') %>

<p id="notice"><%= notice %></p>

<table class="table table-striped">
  
  <thead>
    <tr>
      <th>Nome</th>
      <th>E-mail</th>
      <th>Tipo</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, edit_user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.usertype %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<br>

<%= link_to 'Novo usuário', users_new_path %>

app/views/users/new.html.erb
<div class="divform">
  
  <% provide(:title, 'Novo usuário') %>
  <br>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user, url: signup_path) do |f| %>
  
        <%= render 'shared/error_messages' %>
        
        <%= f.text_field :name, class: 'form-control', placeholder: 'Nome' %>
  
        <%= f.email_field :email, class: 'form-control', placeholder: 'E-mail' %>
  
        <%= f.select(:usertype, [['Administrador', 'A'], ['Usuário', 'U']], {prompt: 'Selecione o tipo'}, {class: 'form-control'}) %>
        
        <%= f.password_field :password, class: 'form-control', placeholder: 'Crie uma senha' %>
  
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: ' Confirme a senha' %>
  
        <%= f.submit "Criar usuário", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <br>
</div>