config/routes.rb
Rails.application.routes.draw do
  
  resources :equipaments
  resources :equipamentusers
  resources :users
  
  root 'sessions#new'
  
  get 'sessions/new'

  get 'users/new'
  
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :sensors
  
  namespace :api , defaults: {format: :json} do 
    namespace :v1 do 
      resources :sensors
    end 
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
  <div class="container">
    <nav>
      <ul>
        <li><%= link_to "About", '#' %></li>
      </ul>
    </nav>
    <small>
      by <a href="">Dynara Rico</a>
    </small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "homeino", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if session[:user_type] == 'A' %>
              <li><%= link_to "Usuários", users_path %></li>
              <li><%= link_to "Equipamentos", equipaments_path %></li>
              <li><%= link_to "Incluir associações", new_equipamentuser_path %></li>
              <li><%= link_to "Lista de equipamentos", equipamentusers_path %></li>
              <% else %>
              <li><%= link_to "Meus equipamentos", equipamentusers_path %></li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
    
    <!--<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js"></script>
    -->
    <%= render 'layouts/shim' %>
  </head>
  
  <body>
    
    <%= render 'layouts/header' %>
    
    <div class="container">
      <%# flash.each do |message_type, message| %>
        <%#= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <%# end %>
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %> 
  </body>

</html>